import { blogPosts } from "@/features/blogs/data/blogs";
import { schools } from "@/features/schools/data/schools";
import { defaultCertificateConfig } from "@/features/certificates/data/certificate";
import { courses } from "@/features/courses/data/courses";
import { courseRegistrations } from "@/features/courses/data/courseRegistrations";
import { events } from "@/features/events/data/events";
import { eventParticipants } from "@/features/events/data/eventParticipants";
import { eventRegistrations } from "@/features/events/data/eventRegistrations";
import { heroSlides } from "@/features/home/data/hero";
import { newsItems } from "@/features/news/data/news";
import { quizSets } from "@/features/quiz/data/quiz";
import { studentClassOptions } from "@/features/shared/data/classes";
import { services } from "@/features/services/data/services";
import { advisors, coreTeam } from "@/features/team/data/team";
import { testimonials } from "@/features/home/data/testimonials";
import { videos } from "@/features/home/data/videos";
import {
  defaultVolunteerConfig,
  volunteerInterestOptions,
} from "@/features/volunteers/data/volunteers";

export type FieldType =
  | "text"
  | "textarea"
  | "richtext"
  | "number"
  | "select"
  | "multiselect"
  | "image"
  | "images"
  | "list"
  | "readonly"
  | "date"
  | "questions"
  | "relation"
  | "pdf";

export interface RelationDef {
  table: TableKey;
  valueField: string;
  labelField: string;
  labelFields?: string[];
  filterField?: string;
  filterValue?: string;
  syncField?: string;
  /** Field of the related doc whose value is stored on this field (instead of the label). */
  storeField?: string;
  /** Show a text input alongside the dropdown so admins can type a custom value. */
  customInput?: boolean;
}

export interface FieldDef {
  name: string;
  label: string;
  type: FieldType;
  options?: string[];
  required?: boolean;
  placeholder?: string;
  list?: boolean;
  min?: number;
  showIf?: Record<string, string>;
  hidden?: boolean;
  relation?: RelationDef;
}

export interface TableConfig {
  key: string;
  label: string;
  singular: string;
  fields: FieldDef[];
  seed: Record<string, unknown>[];
  listColumns: string[];
  single?: boolean;
  readOnly?: boolean;
  deletable?: boolean;
  canCreate?: boolean;
  publicFields?: string[];
  publicCreate?: boolean;
  createFields?: string[];
  editableFields?: string[];
  defaultStatus?: string;
  statusField?: string;
  statusOptions?: string[];
}

export type TableKey =
  | "advisors"
  | "coreteam"
  | "blogs"
  | "events"
  | "hero"
  | "news"
  | "videos"
  | "quizsets"
  | "contacts"
  | "certificates"
  | "certificateconfig"
  | "volunteers"
  | "volunteerconfig"
  | "eventregistrations"
  | "eventparticipants"
  | "testimonials"
  | "courses"
  | "courseregistrations"
  | "services"
  | "servicerequests"
  | "schools"
  | "books"
  | "bookpayments"
  | "quizgroups"
  | "quizwinners"
  | "donationevents"
  | "donations"
  | "itteam"
  | "bookaccess"
  | "readingprogress";

export const tables: Record<TableKey, TableConfig> = {
  advisors: {
    key: "advisors",
    label: "Advisors",
    singular: "Advisor",
    listColumns: ["name", "role", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Jane Doe",
      },
      {
        name: "role",
        label: "Role",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Technical Advisor",
      },
      {
        name: "bio",
        label: "Bio",
        type: "textarea",
        required: true,
        placeholder: "Brief biography of the advisor",
      },
      {
        name: "initials",
        label: "Initials",
        type: "text",
        required: true,
        placeholder: "e.g. JD",
      },
      {
        name: "image",
        label: "Image path",
        type: "image",
        placeholder: "/images/...",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: advisors,
    publicFields: ["name", "role", "bio", "initials", "image", "slug"],
  },
  coreteam: {
    key: "coreteam",
    label: "Core Team",
    singular: "Member",
    listColumns: ["name", "role", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Jane Doe",
      },
      {
        name: "role",
        label: "Role",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Lead Engineer",
      },
      {
        name: "bio",
        label: "Bio",
        type: "textarea",
        required: true,
        placeholder: "Brief bio of the team member",
      },
      {
        name: "initials",
        label: "Initials",
        type: "text",
        required: true,
        placeholder: "e.g. JD",
      },
      {
        name: "image",
        label: "Image path",
        type: "image",
        placeholder: "/images/...",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: coreTeam,
    publicFields: ["name", "role", "bio", "initials", "image", "slug"],
  },
  blogs: {
    key: "blogs",
    label: "Blogs",
    singular: "Blog",
    listColumns: ["title", "author", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "Enter the blog title",
      },
      {
        name: "summary",
        label: "Summary",
        type: "textarea",
        required: true,
        placeholder: "Short summary shown on the blog card",
      },
      {
        name: "excerpt",
        label: "Description",
        type: "richtext",
        required: true,
        placeholder: "Full description shown on the single view",
      },
      {
        name: "category",
        label: "Category",
        type: "text",
        required: true,
        placeholder: "e.g. Technology, Lifestyle",
      },
      {
        name: "author",
        label: "Author",
        type: "text",
        required: true,
        placeholder: "e.g. John Smith",
      },
      {
        name: "authorImage",
        label: "Author image (optional)",
        type: "image",
        placeholder: "/images/...",
      },
      {
        name: "readTime",
        label: "Read time",
        type: "text",
        required: true,
        placeholder: "e.g. 5 min read",
      },
      {
        name: "date",
        label: "Date",
        type: "date",
        required: true,
        placeholder: "e.g. 2026-07-15",
      },
      {
        name: "cardImage",
        label: "Card image",
        type: "image",
        required: true,
        placeholder: "/images/...",
      },
      {
        name: "images",
        label: "Images (multiple)",
        type: "images",
        placeholder: "Upload one or more images",
      },
      {
        name: "externalUrl",
        label: "External link (iframe)",
        type: "text",
        placeholder: "https://example.com/article",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: blogPosts,
    publicFields: [
      "title",
      "summary",
      "excerpt",
      "category",
      "author",
      "authorImage",
      "readTime",
      "date",
      "cardImage",
      "images",
      "externalUrl",
      "slug",
    ],
  },
  events: {
    key: "events",
    label: "Events",
    singular: "Event",
    listColumns: ["title", "status", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "Enter the event title",
      },
      {
        name: "summary",
        label: "Summary",
        type: "textarea",
        required: true,
        placeholder: "Short summary shown on the event card",
      },
      {
        name: "description",
        label: "Description",
        type: "richtext",
        required: true,
        placeholder: "Describe the event details",
      },
      {
        name: "cardImage",
        label: "Card image",
        type: "image",
        required: true,
        placeholder: "/images/...",
      },
      {
        name: "images",
        label: "Images (multiple)",
        type: "images",
        placeholder: "Upload one or more images",
      },
      {
        name: "date",
        label: "Date",
        type: "date",
        required: true,
        placeholder: "e.g. 2026-08-20",
      },
      {
        name: "location",
        label: "Location",
        type: "text",
        required: true,
        placeholder: "e.g. Dhaka, Bangladesh",
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        options: ["Offline", "Online"],
        required: true,
        placeholder: "Select mode",
      },
      {
        name: "category",
        label: "Category",
        type: "text",
        required: true,
        placeholder: "e.g. Workshop, Meetup",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["upcoming", "done"],
        required: true,
        placeholder: "Select status",
      },
      {
        name: "externalUrl",
        label: "External link (iframe)",
        type: "text",
        placeholder: "https://example.com/register",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: events,
    publicFields: [
      "title",
      "summary",
      "description",
      "cardImage",
      "images",
      "date",
      "location",
      "mode",
      "category",
      "status",
      "externalUrl",
      "slug",
    ],
  },
  hero: {
    key: "hero",
    label: "Hero Slides",
    singular: "Slide",
    listColumns: ["title", "accent", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "kicker",
        label: "Kicker",
        type: "text",
        required: true,
        placeholder: "e.g. Welcome to TechPunno",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "Main headline text",
      },
      {
        name: "highlight",
        label: "Highlight",
        type: "text",
        required: true,
        placeholder: "Emphasized text in the title",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: true,
        placeholder: "Supporting description for the slide",
      },
      {
        name: "ctaLabel",
        label: "CTA label",
        type: "text",
        required: true,
        placeholder: "e.g. Learn More",
      },
      {
        name: "ctaHref",
        label: "CTA link",
        type: "text",
        required: true,
        placeholder: "e.g. /about",
      },
      {
        name: "accent",
        label: "Accent",
        type: "select",
        options: ["primary", "secondary"],
        required: true,
        placeholder: "Select accent color",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: heroSlides,
    publicFields: [
      "kicker",
      "title",
      "highlight",
      "description",
      "ctaLabel",
      "ctaHref",
      "accent",
      "slug",
    ],
  },
  news: {
    key: "news",
    label: "News",
    singular: "News",
    listColumns: ["title", "badge", "featured", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "Enter the news headline",
      },
      {
        name: "summary",
        label: "Summary",
        type: "textarea",
        required: true,
        placeholder: "Brief summary of the news",
      },
      {
        name: "content",
        label: "Content",
        type: "richtext",
        required: true,
        placeholder: "Full news article content",
      },
      {
        name: "date",
        label: "Date",
        type: "date",
        required: true,
        placeholder: "e.g. 2026-08-04",
      },
      {
        name: "badge",
        label: "Badge",
        type: "select",
        options: ["Hot", "Update", "Announcement"],
        required: true,
        placeholder: "Select badge type",
      },
      {
        name: "featured",
        label: "Featured",
        type: "select",
        options: ["true", "false"],
        list: true,
        placeholder: "Show in the two big featured cards on the homepage",
      },
      {
        name: "cardImage",
        label: "Card image",
        type: "image",
        required: true,
        placeholder: "/images/...",
      },
      {
        name: "images",
        label: "Images (multiple)",
        type: "images",
        placeholder: "Upload one or more images",
      },
      {
        name: "externalUrl",
        label: "External link (iframe)",
        type: "text",
        placeholder: "https://example.com/news",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: newsItems,
    publicFields: [
      "title",
      "summary",
      "content",
      "date",
      "badge",
      "featured",
      "cardImage",
      "images",
      "externalUrl",
      "slug",
    ],
  },
  videos: {
    key: "videos",
    label: "Videos",
    singular: "Video",
    listColumns: ["title", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "Enter the video title",
      },
      {
        name: "url",
        label: "YouTube URL",
        type: "text",
        required: true,
        placeholder: "https://www.youtube.com/watch?v=...",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: videos,
    publicFields: ["title", "url", "slug"],
  },
  quizsets: {
    key: "quizsets",
    label: "Quiz Sets",
    singular: "Quiz Set",
    listColumns: ["title", "date", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "Enter the quiz set title",
      },
      {
        name: "date",
        label: "Date",
        type: "text",
        list: true,
        placeholder: "e.g. 15 February 2026",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: true,
        placeholder: "Describe what this quiz covers",
      },
      {
        name: "durationSeconds",
        label: "Duration (seconds)",
        type: "number",
        required: true,
        placeholder: "e.g. 300",
      },
      {
        name: "questions",
        label: "Questions",
        type: "questions",
        required: true,
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: quizSets,
    publicFields: [
      "title",
      "date",
      "description",
      "durationSeconds",
      "questions",
      "slug",
    ],
  },
  contacts: {
    key: "contacts",
    label: "Contact Messages",
    singular: "Message",
    readOnly: true,
    listColumns: ["name", "email", "subject", "createdAt", "updatedAt"],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        list: true,
        placeholder: "e.g. Jane Doe",
      },
      {
        name: "email",
        label: "Email",
        type: "text",
        list: true,
        placeholder: "e.g. jane@example.com",
      },
      {
        name: "phone",
        label: "Phone",
        type: "text",
        placeholder: "e.g. +880 1XXXXXXXXX",
      },
      {
        name: "subject",
        label: "Subject",
        type: "text",
        list: true,
        placeholder: "Message subject",
      },
      {
        name: "message",
        label: "Message",
        type: "textarea",
        placeholder: "Type the message body",
      },
      { name: "createdAt", label: "Received", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicCreate: true,
  },
  certificates: {
    key: "certificates",
    label: "Certificates",
    singular: "Certificate",
    readOnly: true,
    deletable: true,
    canCreate: true,
    createFields: ["name", "phone", "percentage", "quizTitle"],
    editableFields: ["name"],
    listColumns: [
      "certificateId",
      "name",
      "percentage",
      "quizTitle",
      "createdAt",
    ],
    fields: [
      {
        name: "certificateId",
        label: "Certificate ID",
        type: "text",
        list: true,
      },
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Jane Doe",
      },
      {
        name: "phone",
        label: "Phone",
        type: "text",
        required: true,
        placeholder: "e.g. 01XXXXXXXXX",
      },
      {
        name: "percentage",
        label: "Percentage",
        type: "number",
        required: true,
        min: 80,
        list: true,
        placeholder: "e.g. 90",
      },
      { name: "score", label: "Score", type: "number", placeholder: "e.g. 9" },
      {
        name: "total",
        label: "Total Questions",
        type: "number",
        placeholder: "e.g. 10",
      },
      {
        name: "quizTitle",
        label: "Quiz",
        type: "relation",
        required: true,
        list: true,
        relation: {
          table: "quizsets",
          valueField: "title",
          storeField: "title",
          labelField: "title",
          labelFields: ["title", "date"],
        },
      },
      {
        name: "date",
        label: "Issue Date",
        type: "text",
        placeholder: "e.g. 5 August 2026",
      },
      { name: "createdAt", label: "Issued", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicCreate: true,
  },
  certificateconfig: {
    key: "certificateconfig",
    label: "Certificate Config",
    singular: "Configuration",
    single: true,
    listColumns: ["eventTitle", "signatoryName", "createdAt", "updatedAt"],
    fields: [
      {
        name: "eventTitle",
        label: "Event title",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Cyber Smart Girls Initiative 2026",
      },
      {
        name: "eventSubtitle",
        label: "Event subtitle",
        type: "text",
        required: true,
        placeholder: "e.g. Cyber Quiz Competition",
      },
      {
        name: "certifyText",
        label: "Certification line",
        type: "text",
        required: true,
        placeholder: "e.g. This is to certify that",
      },
      {
        name: "wishText",
        label: "Wish message",
        type: "textarea",
        required: true,
        placeholder:
          "Use {name} as the recipient name, e.g. We wish {name} all the best.",
      },
      {
        name: "signatoryName",
        label: "Signatory name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Mehedi Hasan",
      },
      {
        name: "signatoryRole",
        label: "Signatory role",
        type: "text",
        required: true,
        placeholder: "e.g. Founder",
      },
      {
        name: "signatoryImage",
        label: "Signature image",
        type: "image",
        placeholder: "/images/certificate/sign-1.png",
      },
      {
        name: "sealTopText",
        label: "Seal top text",
        type: "text",
        required: true,
        placeholder: "e.g. TECH PUNNO",
      },
      {
        name: "sealBottomText",
        label: "Seal bottom text",
        type: "text",
        required: true,
        placeholder: "e.g. CYBER QUIZ 2026",
      },
      {
        name: "qrLabel",
        label: "QR label",
        type: "text",
        required: true,
        placeholder: "e.g. Scan to verify",
      },
    ],
    seed: [defaultCertificateConfig as unknown as Record<string, unknown>],
  },
  volunteers: {
    key: "volunteers",
    label: "Volunteers",
    singular: "Volunteer",
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected", "resigned"],
    listColumns: [
      "volunteerId",
      "fullName",
      "occupation",
      "educationalInstitute",
      "membershipType",
      "joiningDate",
      "status",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      {
        name: "volunteerId",
        label: "Volunteer ID",
        type: "readonly",
        list: true,
      },
      {
        name: "fullName",
        label: "Full Name (পূর্ণ নাম)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "fatherName",
        label: "Father's Name (পিতার নাম)",
        type: "text",
        required: true,
        placeholder: "e.g. Abdul Karim",
      },
      {
        name: "motherName",
        label: "Mother's Name (মাতার নাম)",
        type: "text",
        required: true,
        placeholder: "e.g. Fatema Begum",
      },
      {
        name: "dateOfBirth",
        label: "Date of Birth (জন্ম তারিখ)",
        type: "date",
        required: true,
        placeholder: "e.g. 2005-01-15",
      },
      {
        name: "gender",
        label: "Gender (লিঙ্গ)",
        type: "select",
        options: ["Male", "Female", "Other"],
        required: true,
        placeholder: "Select gender",
      },
      {
        name: "occupation",
        label: "Occupation (পেশা)",
        type: "select",
        options: ["Student", "Job Holder", "Other"],
        required: true,
        list: true,
        placeholder: "Select occupation",
      },
      {
        name: "mobile",
        label: "Mobile Number (মোবাইল নম্বর)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "email",
        label: "Email (ইমেইল)",
        type: "text",
        placeholder: "you@example.com",
      },
      {
        name: "whatsapp",
        label: "WhatsApp Number (হোয়াটসঅ্যাপ নম্বর)",
        type: "text",
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "guardianName",
        label: "Guardian's Name (অভিভাবকের নাম)",
        type: "text",
        required: true,
        placeholder: "Guardian / Emergency contact",
      },
      {
        name: "guardianRelation",
        label: "Guardian Relation (সম্পর্ক)",
        type: "text",
        required: true,
        placeholder: "e.g. Father",
      },
      {
        name: "guardianMobile",
        label: "Guardian Mobile (মোবাইল)",
        type: "text",
        required: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "educationalInstitute",
        label: "Educational Institute (শিক্ষা প্রতিষ্ঠান)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. XYZ School & College / ABC University",
      },
      {
        name: "company",
        label: "Company Name (কোম্পানির নাম)",
        type: "text",
        showIf: { occupation: "Job Holder" },
        placeholder: "e.g. ABC Technologies Ltd.",
      },
      {
        name: "designation",
        label: "Designation / Job Title (পদবি)",
        type: "text",
        showIf: { occupation: "Job Holder" },
        placeholder: "e.g. Software Engineer",
      },
      {
        name: "department",
        label: "Department / Section (বিভাগ/শাখা)",
        type: "text",
        placeholder: "e.g. Science / Class 9",
      },
      {
        name: "educationLevel",
        label: "Highest Education Level (সর্বোচ্চ শিক্ষাগত যোগ্যতা)",
        type: "text",
        required: true,
        placeholder: "e.g. Bachelor of Science in CSE",
      },
      {
        name: "interestAreas",
        label: "Interest Area (আগ্রহের ক্ষেত্র)",
        type: "multiselect",
        options: volunteerInterestOptions,
      },
      {
        name: "membershipType",
        label: "Membership Type (সদস্যপদ ধরন)",
        type: "select",
        options: ["Ambassador", "Volunteer"],
        required: true,
        placeholder: "Select type",
      },
      {
        name: "memberPosition",
        label: "Member Position (পদবি)",
        type: "text",
        placeholder: "e.g. President, General Secretary",
      },
      {
        name: "joiningDate",
        label: "Joining Date (যোগদানের তারিখ)",
        type: "date",
        list: true,
        placeholder: "e.g. 2025-01-15",
      },
      {
        name: "resignedDate",
        label: "Resigned Date (অবস্থান ত্যাগের তারিখ)",
        type: "date",
        list: true,
        placeholder: "e.g. 2026-06-30",
      },
      {
        name: "registrationFee",
        label: "Registration Fee (৳)",
        type: "text",
        placeholder: "e.g. 50",
      },
      {
        name: "paidBy",
        label: "Paid By (পেমেন্ট মাধ্যম)",
        type: "select",
        options: ["Cash", "bKash", "Nagad"],
        placeholder: "Select method",
      },
      {
        name: "transactionId",
        label: "Transaction ID",
        type: "text",
        placeholder: "e.g. 8P7Q2R3A",
      },
      { name: "image", label: "Photo (ছবি)", type: "image" },
      {
        name: "officeNote",
        label: "Office Note (অফিস নোট)",
        type: "textarea",
        placeholder: "Internal notes",
      },
      {
        name: "approvedBy",
        label: "Approved By (অনুমোদনকারী)",
        type: "select",
        options: ["Founder", "Co-Founder", "Team Leader", "Panel Member"],
        placeholder: "Select approver",
      },
      {
        name: "status",
        label: "Status (অবস্থা)",
        type: "select",
        options: ["pending", "approved", "rejected", "resigned"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Registered", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicFields: [
      "fullName",
      "educationalInstitute",
      "educationLevel",
      "membershipType",
      "memberPosition",
      "image",
      "status",
      "volunteerId",
      "joiningDate",
      "resignedDate",
      "company",
      "department",
      "designation",
    ],
  },
  volunteerconfig: {
    key: "volunteerconfig",
    label: "Volunteer Config",
    singular: "Configuration",
    single: true,
    listColumns: ["bkashNumber", "registrationFee", "createdAt", "updatedAt"],
    fields: [
      {
        name: "bkashNumber",
        label: "bKash Number (পেমেন্ট নম্বর)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "bkashQr",
        label: "bKash QR Code Image",
        type: "image",
        placeholder: "/images/uploads/...",
      },
      {
        name: "registrationFee",
        label: "Registration Fee (৳)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 50",
      },
      { name: "createdAt", label: "Created", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [defaultVolunteerConfig as unknown as Record<string, unknown>],
    publicFields: ["bkashNumber", "bkashQr", "registrationFee"],
  },
  eventregistrations: {
    key: "eventregistrations",
    label: "Event Registers",
    singular: "Event Registration",
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    listColumns: [
      "fullName",
      "mobile",
      "institution",
      "className",
      "eventTitle",
      "status",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      {
        name: "eventId",
        label: "Event ID",
        type: "text",
        hidden: true,
        placeholder: "Event id or slug",
      },
      {
        name: "eventTitle",
        label: "Event",
        type: "relation",
        required: true,
        list: true,
        placeholder: "Select an event",
        relation: {
          table: "events",
          valueField: "id",
          labelField: "title",
          labelFields: ["title", "location"],
          filterField: "status",
          filterValue: "done",
          syncField: "eventId",
        },
      },
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "fatherName",
        label: "Father's Name",
        type: "text",
        required: true,
        placeholder: "e.g. Abdul Karim",
      },
      {
        name: "motherName",
        label: "Mother's Name",
        type: "text",
        required: true,
        placeholder: "e.g. Fatema Begum",
      },
      {
        name: "mobile",
        label: "Mobile Number",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "className",
        label: "Class",
        type: "select",
        options: studentClassOptions,
        required: true,
        list: true,
        placeholder: "Select class",
      },
      {
        name: "institution",
        label: "School/College Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. XYZ School & College",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "approved", "rejected"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Registered", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: eventRegistrations,
    publicCreate: true,
  },
  eventparticipants: {
    key: "eventparticipants",
    label: "Event Participants",
    singular: "Participant",
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    listColumns: [
      "fullName",
      "mobile",
      "institution",
      "className",
      "eventTitle",
      "status",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      {
        name: "eventId",
        label: "Event ID",
        type: "text",
        hidden: true,
        placeholder: "Event id or slug",
      },
      {
        name: "eventTitle",
        label: "Event",
        type: "relation",
        required: true,
        list: true,
        placeholder: "Select an event",
        relation: {
          table: "events",
          valueField: "id",
          labelField: "title",
          labelFields: ["title", "location"],
          filterField: "status",
          filterValue: "done",
          syncField: "eventId",
        },
      },
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "fatherName",
        label: "Father's Name",
        type: "text",
        required: true,
        placeholder: "e.g. Abdul Karim",
      },
      {
        name: "motherName",
        label: "Mother's Name",
        type: "text",
        required: true,
        placeholder: "e.g. Fatema Begum",
      },
      {
        name: "mobile",
        label: "Mobile Number",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "className",
        label: "Class",
        type: "select",
        options: studentClassOptions,
        required: true,
        list: true,
        placeholder: "Select class",
      },
      {
        name: "institution",
        label: "School/College Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. XYZ School & College",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "approved", "rejected"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Added", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: eventParticipants,
    publicFields: [
      "fullName",
      "className",
      "institution",
      "eventId",
      "eventTitle",
      "status",
    ],
  },
  testimonials: {
    key: "testimonials",
    label: "Testimonials",
    singular: "Testimonial",
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    listColumns: ["name", "institution", "rating", "status", "createdAt", "updatedAt"],
    fields: [
      {
        name: "name",
        label: "Student Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "institution",
        label: "Educational Institution",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. XYZ School & College",
      },
      {
        name: "message",
        label: "Review",
        type: "textarea",
        required: true,
        placeholder: "Write the student's review here",
      },
      {
        name: "rating",
        label: "Rating (1-5)",
        type: "number",
        min: 1,
        placeholder: "e.g. 5",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "approved", "rejected"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Submitted", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: testimonials,
    publicFields: ["name", "institution", "message", "rating", "status"],
    publicCreate: true,
  },
  courses: {
    key: "courses",
    label: "Courses",
    singular: "Course",
    listColumns: ["title", "category", "status", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "Enter the course title",
      },
      {
        name: "summary",
        label: "Summary",
        type: "textarea",
        required: true,
        placeholder: "Short summary shown on the course card",
      },
      {
        name: "description",
        label: "Description",
        type: "richtext",
        required: true,
        placeholder: "Full course description",
      },
      {
        name: "category",
        label: "Category",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Digital Skills, Coding",
      },
      {
        name: "duration",
        label: "Duration",
        type: "text",
        required: true,
        placeholder: "e.g. 4 weeks",
      },
      {
        name: "schedule",
        label: "Schedule",
        type: "text",
        required: true,
        placeholder: "e.g. Friday & Saturday, 4:00 PM - 6:00 PM",
      },
      {
        name: "fees",
        label: "Fees",
        type: "text",
        required: true,
        placeholder: "e.g. Free or ৳ 500",
      },
      {
        name: "image",
        label: "Card image",
        type: "image",
        placeholder: "/images/...",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["open", "upcoming", "completed"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: courses,
    publicFields: [
      "title",
      "summary",
      "description",
      "category",
      "duration",
      "schedule",
      "fees",
      "image",
      "status",
      "slug",
    ],
  },
  courseregistrations: {
    key: "courseregistrations",
    label: "Course Registers",
    singular: "Course Registration",
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    listColumns: [
      "fullName",
      "mobile",
      "institution",
      "className",
      "courseTitle",
      "status",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      {
        name: "courseId",
        label: "Course ID",
        type: "text",
        placeholder: "Course id or slug",
      },
      {
        name: "courseTitle",
        label: "Course Title",
        type: "text",
        list: true,
        placeholder: "e.g. Digital Literacy Basics",
      },
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "fatherName",
        label: "Father's Name",
        type: "text",
        required: true,
        placeholder: "e.g. Abdul Karim",
      },
      {
        name: "motherName",
        label: "Mother's Name",
        type: "text",
        required: true,
        placeholder: "e.g. Fatema Begum",
      },
      {
        name: "mobile",
        label: "Mobile Number",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "className",
        label: "Class",
        type: "select",
        options: studentClassOptions,
        required: true,
        list: true,
        placeholder: "Select class",
      },
      {
        name: "institution",
        label: "School/College Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. XYZ School & College",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "approved", "rejected"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Registered", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: courseRegistrations,
    publicCreate: true,
  },
  services: {
    key: "services",
    label: "Services",
    singular: "Service",
    listColumns: ["title", "icon", "charge", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Social Media Account Recovery",
      },
      {
        name: "icon",
        label: "Icon (emoji)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 🔐",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: true,
        placeholder: "Describe the service",
      },
      {
        name: "charge",
        label: "Service Charge",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. আলোচনা সাপেক্ষে",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: services as unknown as Record<string, unknown>[],
    publicFields: ["title", "icon", "description", "charge", "slug"],
  },
  servicerequests: {
    key: "servicerequests",
    label: "Service Requests",
    singular: "Service Request",
    readOnly: true,
    defaultStatus: "Pending",
    statusField: "status",
    statusOptions: [
      "Pending",
      "Reviewing",
      "Contacted",
      "In Progress",
      "Completed",
      "Cancelled",
    ],
    listColumns: [
      "requestId",
      "service",
      "name",
      "phone",
      "email",
      "status",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      {
        name: "requestId",
        label: "Request ID",
        type: "readonly",
        list: true,
      },
      {
        name: "service",
        label: "Service",
        type: "text",
        required: true,
        list: true,
        placeholder: "Service name",
      },
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "phone",
        label: "Mobile Number",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 01XXXXXXXXX",
      },
      {
        name: "email",
        label: "Email",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. rahim@example.com",
      },
      {
        name: "description",
        label: "Problem Description",
        type: "textarea",
        required: true,
        placeholder: "Describe the problem or request",
      },
      {
        name: "links",
        label: "Links / Additional Info",
        type: "text",
        placeholder: "https://... or any relevant info",
      },
      {
        name: "contactMethod",
        label: "Preferred Contact Method",
        type: "select",
        options: ["Phone Call", "WhatsApp", "Email", "Facebook Messenger"],
        required: true,
        list: true,
        placeholder: "Select preferred method",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          "Pending",
          "Reviewing",
          "Contacted",
          "In Progress",
          "Completed",
          "Cancelled",
        ],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Submitted", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicCreate: true,
    publicFields: ["requestId", "service", "status"],
  },
  schools: {
    key: "schools",
    label: "Schools (Network)",
    singular: "School",
    defaultStatus: "unpublished",
    statusField: "status",
    statusOptions: ["published", "unpublished"],
    listColumns: [
      "name",
      "district",
      "seminarDate",
      "participants",
      "consentStatus",
      "badge",
      "status",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      {
        name: "name",
        label: "School Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Gopalganj Model High School",
      },
      {
        name: "logo",
        label: "Logo / Photo",
        type: "image",
        placeholder: "Upload the school logo or photo",
      },
      {
        name: "district",
        label: "District",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Gopalganj",
      },
      {
        name: "upazila",
        label: "Upazila",
        type: "text",
        placeholder: "e.g. Gopalganj Sadar",
      },
      {
        name: "seminarDate",
        label: "Seminar Date",
        type: "date",
        required: true,
        list: true,
        placeholder: "e.g. 2026-08-18",
      },
      {
        name: "participants",
        label: "Number of Participants",
        type: "number",
        required: true,
        list: true,
        placeholder: "e.g. 240",
      },
      {
        name: "grades",
        label: "Participating Classes",
        type: "list",
        placeholder: "e.g. Class 8, Class 9, Class 10 (one per line)",
      },
      {
        name: "images",
        label: "Seminar Photos",
        type: "images",
        placeholder: "Upload one or more seminar photos",
      },
      {
        name: "ictTeacherName",
        label: "ICT Teacher Name",
        type: "text",
        placeholder: "e.g. Mahmudul Hasan",
      },
      {
        name: "ictTeacherRole",
        label: "ICT Teacher Designation",
        type: "text",
        placeholder: "e.g. Assistant Teacher (ICT)",
      },
      {
        name: "ictTeacherImage",
        label: "ICT Teacher Photo",
        type: "image",
        placeholder: "Upload the ICT teacher's photo",
      },
      {
        name: "badge",
        label: "Badge",
        type: "select",
        options: ["Seminar Completed", "Cyber Awareness Partner"],
        required: true,
        list: true,
        placeholder: "Select badge type",
      },

      {
        name: "advisorName",
        label: "ICT Advisor Name",
        type: "text",
        placeholder: "e.g. Mahmudul Hasan",
      },
      {
        name: "advisorDesignation",
        label: "ICT Advisor Designation",
        type: "text",
        placeholder: "e.g. ICT Teacher",
      },
      {
        name: "advisorImage",
        label: "ICT Advisor Photo",
        type: "image",
        placeholder: "Upload the ICT advisor's photo",
      },
      {
        name: "advisorJoinedDate",
        label: "ICT Advisor Joined Date",
        type: "date",
        placeholder: "e.g. 2026-08-22",
      },
      {
        name: "advisorApproved",
        label: "ICT Advisor Approved",
        type: "select",
        options: ["false", "true"],
        required: true,
        placeholder: "Has the ICT teacher & school authority consented?",
      },

      {
        name: "headName",
        label: "Head Teacher Name",
        type: "text",
        placeholder: "e.g. Md. Anowar Hossain",
      },
      {
        name: "headDesignation",
        label: "Head Teacher Designation",
        type: "text",
        placeholder: "e.g. Headmaster",
      },
      {
        name: "headImage",
        label: "Head Teacher Photo",
        type: "image",
        placeholder: "Upload the head teacher's photo",
      },
      {
        name: "headTestimonial",
        label: "Head Teacher Testimonial",
        type: "textarea",
        placeholder:
          "2–5 line testimonial from the school head. Publish only with their consent.",
      },
      {
        name: "headTestimonialPhoto",
        label: "Handwritten Testimonial Photo",
        type: "image",
        placeholder: "Upload the handwritten testimonial photo (optional)",
      },
      {
        name: "testimonialApproved",
        label: "Testimonial Approved",
        type: "select",
        options: ["false", "true"],
        required: true,
        placeholder: "Has the head teacher consented to publishing?",
      },

      {
        name: "timeline",
        label: "Activity Timeline",
        type: "list",
        placeholder:
          'One activity per line, format: Month Year | Activity  e.g. August 2026 | Cyber Awareness Seminar',
      },

      {
        name: "consentStatus",
        label: "Consent Status",
        type: "select",
        options: ["pending", "granted", "denied"],
        required: true,
        list: true,
        placeholder: "Select consent status",
      },
      {
        name: "status",
        label: "Publish Status",
        type: "select",
        options: ["published", "unpublished"],
        required: true,
        list: true,
        placeholder: "Select publish status",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
      { name: "createdAt", label: "Created", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: schools as unknown as Record<string, unknown>[],
    publicFields: [
      "name",
      "logo",
      "district",
      "upazila",
      "seminarDate",
      "participants",
      "grades",
      "images",
      "ictTeacherName",
      "ictTeacherRole",
      "ictTeacherImage",
      "badge",
      "advisorName",
      "advisorDesignation",
      "advisorImage",
      "advisorJoinedDate",
      "advisorApproved",
      "headName",
      "headDesignation",
      "headImage",
      "headTestimonial",
      "headTestimonialPhoto",
      "testimonialApproved",
      "timeline",
      "consentStatus",
      "status",
      "slug",
    ],
  },
  books: {
    key: "books",
    label: "Books",
    singular: "Book",
    defaultStatus: "published",
    statusField: "status",
    statusOptions: ["published", "unpublished"],
    listColumns: ["title", "author", "isfree", "price", "status", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "title",
        label: "Book Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Cyber Security Basics",
      },
      {
        name: "author",
        label: "Author Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Mehedi Hasan",
      },
      {
        name: "description",
        label: "Short Description",
        type: "textarea",
        required: true,
        placeholder: "Short description shown on the book card",
      },
      {
        name: "pageCount",
        label: "Page Number",
        type: "number",
        placeholder: "e.g. 120",
      },
      {
        name: "isfree",
        label: "Book Type",
        type: "select",
        options: ["Free", "Paid"],
        required: true,
        list: true,
        placeholder: "Select Free or Paid",
      },
      {
        name: "price",
        label: "Price (৳)",
        type: "text",
        list: true,
        placeholder: "e.g. 150",
      },
      {
        name: "cover",
        label: "Book Cover",
        type: "image",
        required: true,
        placeholder: "Upload book cover image",
      },
      {
        name: "pdf",
        label: "Book PDF",
        type: "pdf",
        placeholder: "Attach the book content as a PDF (max 100MB)",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["published", "unpublished"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
      { name: "createdAt", label: "Created", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicFields: [
      "title",
      "author",
      "description",
      "pageCount",
      "isfree",
      "price",
      "cover",
      "status",
      "slug",
    ],
  },
  bookpayments: {
    key: "bookpayments",
    label: "Book Payments",
    singular: "Book Payment",
    readOnly: true,
    deletable: true,
    canCreate: false,
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    listColumns: [
      "fullName",
      "mobile",
      "bookTitle",
      "amount",
      "paymentMethod",
      "senderNumber",
      "transactionId",
      "status",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      {
        name: "userId",
        label: "User ID",
        type: "text",
        hidden: true,
      },
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "mobile",
        label: "Mobile Number",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "email",
        label: "Email",
        type: "text",
        placeholder: "user@example.com",
      },
      {
        name: "bookId",
        label: "Book ID",
        type: "text",
        hidden: true,
      },
      {
        name: "bookTitle",
        label: "Book",
        type: "relation",
        required: true,
        list: true,
        placeholder: "Select a book",
        relation: {
          table: "books",
          valueField: "id",
          labelField: "title",
          labelFields: ["title", "author"],
          syncField: "bookId",
        },
      },
      {
        name: "paymentMethod",
        label: "Payment Method",
        type: "select",
        options: ["bKash", "Nagad"],
        required: true,
        list: true,
        placeholder: "Select method",
      },
      {
        name: "senderNumber",
        label: "Sender Number",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "transactionId",
        label: "Transaction ID",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 8P7Q2R3A",
      },
      {
        name: "amount",
        label: "Amount (৳)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 150",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "approved", "rejected"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Submitted", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicCreate: true,
  },
  quizgroups: {
    key: "quizgroups",
    label: "Quiz Groups",
    singular: "Quiz Group",
    listColumns: ["title", "quizTitle", "slug", "createdAt"],
    fields: [
      {
        name: "title",
        label: "Group Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Group A",
      },
      {
        name: "quizTitle",
        label: "Quiz",
        type: "relation",
        required: true,
        list: true,
        placeholder: "Select a quiz",
        relation: {
          table: "quizsets",
          valueField: "title",
          storeField: "title",
          labelField: "title",
          labelFields: ["title", "date"],
        },
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: [],
    publicFields: ["title", "quizTitle", "slug"],
  },
  quizwinners: {
    key: "quizwinners",
    label: "Quiz Winners",
    singular: "Quiz Winner",
    listColumns: ["quizTitle", "groupName", "position", "name", "className", "school", "createdAt"],
    fields: [
      {
        name: "quizTitle",
        label: "Quiz",
        type: "relation",
        required: true,
        list: true,
        placeholder: "Select a quiz",
        relation: {
          table: "quizsets",
          valueField: "title",
          storeField: "title",
          labelField: "title",
          labelFields: ["title", "date"],
          customInput: true,
        },
      },
      {
        name: "groupName",
        label: "Quiz Group",
        type: "relation",
        placeholder: "Select quiz group (optional)",
        list: true,
        relation: {
          table: "quizsets",
          valueField: "title",
          storeField: "title",
          labelField: "title",
          labelFields: ["title", "date"],
          customInput: true,
        },
      },
      {
        name: "position",
        label: "Position",
        type: "select",
        options: ["1st", "2nd", "3rd"],
        required: true,
        list: true,
        placeholder: "Select position",
      },
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "Winner's full name",
      },
      {
        name: "className",
        label: "Class",
        type: "text",
        list: true,
        placeholder: "e.g. Class 9",
      },
      {
        name: "school",
        label: "School",
        type: "text",
        list: true,
        placeholder: "e.g. XYZ School & College",
      },
      {
        name: "photo",
        label: "Photo",
        type: "image",
        placeholder: "Upload winner photo",
      },
      { name: "createdAt", label: "Added", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicFields: ["quizTitle", "groupName", "position", "name", "className", "school", "photo"],
  },
  donationevents: {
    key: "donationevents",
    label: "Donation Events",
    singular: "Donation Event",
    listColumns: ["title", "target", "collected", "slug", "createdAt"],
    fields: [
      {
        name: "title",
        label: "Event Title",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Cyber Awareness Seminar",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Short description of the event",
      },
      {
        name: "target",
        label: "Target Amount (৳)",
        type: "number",
        required: true,
        list: true,
        placeholder: "e.g. 20000",
      },
      {
        name: "collected",
        label: "Collected Amount (৳)",
        type: "number",
        list: true,
        placeholder: "e.g. 12000",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: [],
    publicFields: ["title", "description", "target", "collected", "slug"],
  },
  donations: {
    key: "donations",
    label: "Donations",
    singular: "Donation",
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    listColumns: ["fullName", "mobile", "amount", "eventName", "paymentMethod", "anonymous", "status", "createdAt"],
    fields: [
      {
        name: "donationId",
        label: "Donation ID",
        type: "readonly",
        list: true,
      },
      {
        name: "fullName",
        label: "Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Rahim Uddin",
      },
      {
        name: "mobile",
        label: "Mobile Number",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "amount",
        label: "Amount (৳)",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. 500",
      },
      {
        name: "eventName",
        label: "Event",
        type: "text",
        list: true,
        placeholder: "e.g. General Donation",
      },
      {
        name: "paymentMethod",
        label: "Payment Method",
        type: "select",
        options: ["bKash", "Nagad"],
        required: true,
        list: true,
        placeholder: "Select method",
      },
      {
        name: "senderNumber",
        label: "Sender Number",
        type: "text",
        placeholder: "e.g. 017XXXXXXXX",
      },
      {
        name: "transactionId",
        label: "Transaction ID",
        type: "text",
        placeholder: "e.g. 8P7Q2R3A",
      },
      {
        name: "anonymous",
        label: "Anonymous Donation",
        type: "select",
        options: ["No", "Yes"],
        required: true,
        list: true,
        placeholder: "Show name publicly?",
      },
      {
        name: "location",
        label: "Location",
        type: "text",
        placeholder: "e.g. Dhaka",
      },
      {
        name: "image",
        label: "Photo / Logo",
        type: "image",
        placeholder: "Optional image or logo",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "approved", "rejected"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Submitted", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
    publicCreate: true,
    publicFields: [
      "fullName",
      "amount",
      "eventName",
      "anonymous",
      "location",
      "image",
      "status",
    ],
  },
  itteam: {
    key: "itteam",
    label: "IT Team",
    singular: "IT Team Member",
    listColumns: ["name", "role", "post", "experience", "slug", "createdAt", "updatedAt"],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Jane Doe",
      },
      {
        name: "role",
        label: "Role",
        type: "text",
        required: true,
        list: true,
        placeholder: "e.g. Developer",
      },
      {
        name: "post",
        label: "Post",
        type: "text",
        list: true,
        placeholder: "e.g. Lead Developer",
      },
      {
        name: "experience",
        label: "Experience",
        type: "text",
        list: true,
        placeholder: "e.g. 4 years",
      },
      {
        name: "bio",
        label: "Bio",
        type: "textarea",
        placeholder: "Short bio",
      },
      {
        name: "image",
        label: "Photo",
        type: "image",
        placeholder: "Upload team member photo",
      },
      {
        name: "initials",
        label: "Initials",
        type: "text",
        placeholder: "e.g. JD",
      },
      { name: "slug", label: "Slug", type: "readonly", list: true },
    ],
    seed: [],
    publicFields: ["name", "role", "post", "experience", "bio", "image", "initials", "slug"],
  },
  bookaccess: {
    key: "bookaccess",
    label: "Book Access",
    singular: "Book Access",
    defaultStatus: "pending",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    listColumns: ["fullName", "mobile", "bookTitle", "status", "createdAt"],
    fields: [
      {
        name: "userId",
        label: "User ID",
        type: "text",
        hidden: true,
      },
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        list: true,
      },
      {
        name: "mobile",
        label: "Mobile",
        type: "text",
        list: true,
      },
      {
        name: "bookTitle",
        label: "Book",
        type: "text",
        required: true,
        list: true,
        placeholder: "Book title",
      },
      {
        name: "bookId",
        label: "Book ID",
        type: "text",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "approved", "rejected"],
        required: true,
        list: true,
        placeholder: "Select status",
      },
      { name: "createdAt", label: "Created", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
  },
  readingprogress: {
    key: "readingprogress",
    label: "Reading Progress",
    singular: "Reading Progress",
    listColumns: ["fullName", "bookTitle", "page", "progress", "updatedAt"],
    fields: [
      {
        name: "userId",
        label: "User ID",
        type: "text",
        hidden: true,
      },
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        list: true,
      },
      {
        name: "bookTitle",
        label: "Book",
        type: "text",
        list: true,
      },
      {
        name: "bookId",
        label: "Book ID",
        type: "text",
      },
      {
        name: "page",
        label: "Last Page",
        type: "number",
        list: true,
      },
      {
        name: "progress",
        label: "Progress (%)",
        type: "number",
        list: true,
      },
      { name: "createdAt", label: "Created", type: "readonly", list: true },
      { name: "updatedAt", label: "Updated", type: "readonly", list: true },
    ],
    seed: [],
  },
};

export function isTableKey(key: string): key is TableKey {
  return key in tables;
}

export const tableKeys = Object.keys(tables) as TableKey[];

